Repository Sandstorm-Station/Sandstorm-Station-13, pull requests merged in 2020-09, with the labels that each got.

#60 Ports tgstation/53371
  code/modules/client/client_procs.dm
  code/modules/unit_tests/character_saving.dm
  tgui/packages/tgui/public/tgui-panel.bundle.js
Labels: UI

#63 Drakeborgs + plushies problem solving
  code/game/objects/items/miscellaneous.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/obj/Plush_Drake.dmi
  sandcode/code/game/objects/items/plushes/goat_boss.dm
  sandcode/code/game/objects/items/plushes/plushes.dm
  sandcode/icons/mob/cyborg/Drakeborg-licensing.txt
  sandcode/icons/mob/cyborg/drakemech.dmi
  sandcode/icons/obj/license.txt
  sandcode/icons/obj/plushes.dmi
  sandcode/icons/obj/plushies.dmi
  tgstation.dme
Labels: Code Improvement, Fix, Revert, Sprites, documentation

#67 Solves some stuff missing from the new chat
  interface/stylesheet.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/public/tgui-panel.bundle.css
  tgui/packages/tgui/public/tgui-panel.bundle.js
Labels: UI

#69 Many borg changes (seriously)
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs/mechfabricator_designs.dm
  sandcode/code/datums/ai_laws.dm
  sandcode/code/game/objects/items/borg_shapeshifter.dm
  sandcode/code/game/objects/items/robot/robot_upgrades.dm
  sandcode/code/game/objects/items/stacks/sheets/glass.dm
  sandcode/code/game/objects/items/stacks/sheets/mineral.dm
  sandcode/code/game/objects/items/stacks/sheets/sheet_types.dm
  sandcode/code/game/objects/structures/ghost_role_spawners.dm
  sandcode/code/modules/mob/living/silicon/robot/robot.dm
  sandcode/code/modules/mob/living/silicon/robot/robot_modules.dm
  sandcode/code/modules/reagents/reagent_containers/borghydro.dm
  sandcode/code/modules/research/designs/mechfabricator_designs.dm
  sandcode/code/modules/research/techweb/nodes/robotics_nodes.dm
  sandcode/code/modules/ruins/spaceruin_code/hilbertshotel.dm
  sandcode/icons/obj/drinks.dmi
  sandcode/icons/obj/machines/robot_storage.dmi
  tgstation.dme
Labels: Feature, Map Edit, Sprites, Tweak

#76 Revert "Runechat fix"
  code/datums/chatmessage.dm
Labels: Revert

#81 Fix send2chat
  code/__HELPERS/unsorted.dm
Labels: Fix
